package domain

// imports
import (
	"errors";
	"time";
	"github.com/dgrijalva/jwt-go";
)

// task item
type Task struct {
	ID            string            // unique identifier of task generated by mongodb
	Title         string            // title of task
	Description   string            // description of task
	DueDate       time.Time         // due date of task (ISO 8601 format)
	Status        string      		// status of task
}

// user item
type User struct {
	ID           string             // mongodb's unique identifier for users 
	Username     string             // username 
	Password     string      		// password (hashed before storage)
	Role         string      		// user role (role/user)
}

// credential item
type Credentials struct {
	Username 	 string              // login username 
    Password 	 string 	         // login password 

}

// task repository interface 
type TaskRepository interface {
	CreateTask(task *Task) (*Task, error)                     // create new task with validation
	DeleteTask(taskID string) error                           // delete existing task or return error if not found
	GetAllTasks() ([]Task, error)         			  // get all tasks in the system
	GetTaskByID(taskID string) (*Task, error) 		  // get specific task by id or return error if not found
	UpdateTask(taskID string, task *Task) (*Task, error)      // update existing task or return error if not found
}

// user repository interface
type UserRepository interface {    
	CreateUser(user *User) error                              // create new user with validation
	GetByUsername(username string) (*User, error)             // get specific user by username or return error if not found
	GetUserById(id string) (*User, error)                     // get specific user by id or return error if not found
	GetUserCount() (int64, error)                             // get total user count or return error 
	UpdateRole(id string, role string) error                  // update user's role to admin or return error if not found                            
}

// user usecase interface 
type UserUseCase interface {
	Register(user *User) error                                       // register user with validation
	Login(credentials *Credentials) (string, *User, error)           // authenticate user with validation
	PromoteToAdmin(userID string) error                              // promote user to admin with validation
}

// task usecase interface
type TaskUseCase interface {
	CreateTask(task *Task) (*Task, error)                       // create new task with validation
	DeleteTask(taskID string) error                 			// delete existing task or return error if not found
	GetAllTasks() ([]Task, error)         					    // get all tasks in the system
	GetTaskByID(taskID string) (*Task, error) 					// get specific task by id or return error if not found
	UpdateTask(taskID string, task *Task) (*Task, error)        // update existing task or return error if not found
}

// jwt service interface
type JWTService interface {
	GenerateToken(userID, username, role string) (string, error)       // generate token or return error
	ValidateToken(tokenStr string) (*jwt.Token, error)                 // validate token or return error
}

// password service interface
type PasswordService interface {
	HashPassword(password string) (string, error)       // hash password or return error
	CheckPassword(hashed, plain string) bool            // check password and return bool (true/false)
}

// custom errors
var (
	ErrTaskNotFound      = errors.New("task not found")              // custom task not found error
	ErrInvalidTaskID     = errors.New("invalid task ID")             // custom invalid task id error
	ErrUserExists        = errors.New("user already exists")         // custom user exists error
	ErrUserNotFound      = errors.New("user not found")              // custom user not found error
	ErrInvalidUserID     = errors.New("invalid user ID")             // custom invalid user id error
	ErrInvalidCredentials = errors.New("invalid credentials")        // custom invalid credentials error
	ErrUnauthorized      = errors.New("unauthorized access")         // custom unauthorized access error
)
